### PR TITLE
Added height to the featured status

### PR DESCRIPTION
**Pull request by dinnu93**

### CODE REVIEW

**Comment by digitarald** [comment]
@dinnu93: Can you elaborate on what this fixes?

**Comment by dinnu93** [comment]
In the home page https://platatus.herokuapp.com/ the icons on the right seem to be chopped off in the bottom part, so gave a little bit of height to extend it to make it look good.

**Comment by digitarald** [comment]
Thank you! This is indeed reoccurring feedback that I am trying to address in #180 . The commits should come in today with the new status design.

I am closing this for now but we can revisit when the new layout it up.

**Comment by dinnu93** [comment]
Thanks for the quick reply I'll search for other issues and contribute.

**Pull request closed without merging**
