### PR TITLE
Add opera_status to Web Bluetooth

### PR DESCRIPTION
**Pull request by beaufortfrancois**
FYI @tommythorsen @perja12

### CODE REVIEW

**Comment by digitarald** [comment]
I understand that Opera updates their status on chromestatus, but it seems like we only get a status when it shipped in Opera. Would it make sense to add their status to https://www.chromestatus.com/features/5264933985976320?

**Comment by marco-c** [comment]
Harald, is Opera maintaining chromestatus.com as well? Maybe it would make sense to ask them to provide more detailed info.

**Comment by digitarald** [comment]
[Tweeted](https://twitter.com/digitarald/status/694971023796506624) to verify

**Comment by mathiasbynens** [comment]
I regularly update the ChromeStatus entries for Opera (and have been for two years now).

Although Opera uses Chromium (just like Chrome) there are sometimes differences between implementation status, so it would makes sense to have separate database entries IMHO. Currently I just add “Opera status: in development” to the “general description” field as a poor work-around :(

**Comment by beaufortfrancois** [comment]
Here's the issue to show Opera status in chromestatus.com: https://github.com/GoogleChrome/chromium-dashboard/issues/263
In the mean time, can we merge this PR?

**Comment by marco-c** [comment]
I'm not sure what we should do here. All the features where Chrome's status is `in development`, Opera status's is `no signals`. Maybe we should always use `in development` for Opera's status for features where Chrome's status is `in development`, as a poor workaround (then, if it's a Chrome-only feature, the status between Chrome and Opera will be different as soon as Chrome ships the feature).

**Comment by digitarald** [comment]
Fixed in #319

**Pull request closed without merging**
