### PR TITLE
Populate spec status from chrome data.

### LINKED ISSUE #42: Track spec status per feature
Fill back from chrome data.

### PR DESCRIPTION
**Pull request by brendandahl**
Fixes #42

### CODE REVIEW

**Comment by digitarald** [comment]
Could we normalize the text? It would allow us to make color-coding easier.

**Comment by brendandahl** [comment]
```
De-facto standard
Editor's draft
Established standard
No public standards discussion
Public discussion
Working draft or equivalent
```

**Comment by digitarald** [comment]
@brendandahl any idea where `De-facto standard` and `Established standard` differ?

**Comment by brendandahl** [comment]
> @brendandahl any idea where De-facto standard and Established standard differ?

"de-facto" is the when it's implemented the same by all browsers, but not standardized.

**Pull request merged**
