### PR TITLE
WIP: Refresh page on sw update

### PR DESCRIPTION
**Pull request by digitarald**
WIP because it crashes Chrome Canary regularly.

@mykmelez @delapuente r?

### CODE REVIEW

**Comment by marco-c** [comment]
You could use the code from the oghliner's template: https://github.com/mozilla/oghliner/blob/master/templates/app/scripts/offline-manager.js

**Comment by digitarald** [comment]
@marco-c I used it before and saw the same crashing behavior. This code also basically does the same, just unrolled in promises.

**Comment by digitarald** [comment]
Ben Kelly is on the weird behaviour I caught with an extra event listener on the current controller: https://bugzilla.mozilla.org/show_bug.cgi?id=1226443#c7

**Comment by digitarald** [comment]
Merging now, see if this causes more crashes

**Pull request merged**
