### PR TITLE
Better status and header

### PR DESCRIPTION
**Pull request by digitarald**
- [x] New header
  Header
- [x] Switch from horizontally cut off icons to vertically hidden icons that reveal on hover/focus
  - Half icons for mobile landscape
    Half icons for mobile landscape
  - Full icons for tablet and up
    Full icons
  - Hover state reveals full browser state
    Hover state
- [x] Release channel icons (inline icon into the project) - *Marco has a patch for this ready which we'll have to rebase when this lands*

Missing optimizations:
- [x] Text contrast/legibility
- [x] Hover/highlight style for status

### CODE REVIEW

**Comment by marco-c** [comment]
I submitted #177 for release channel icons.

**Comment by digitarald** [comment]
Yes @marco-c, there is a conflict inbound if we merge yours.

**Comment by marco-c** [comment]
Nice! In landscape mode it's hard to tell that the browser icons are links.

**Comment by marco-c** [comment]
The text in the header isn't really readable for me.

**Comment by marco-c** [comment]
header

**Comment by digitarald** [comment]
For reference: https://www.browserstack.com/screenshots/7d9df9689ab56157306c90d8ab160975583e0153

**Comment by digitarald** [comment]
Happy Thanksgiving

**Pull request merged**
