### PR TITLE
Improve Intern integration

### PR DESCRIPTION
**Pull request by TimAbraldes**
- Create "tests/support/var" dir for Selenium JAR and logs
- Download Selenium if not found
- Create Page Object for handling the main page
- Add first dummy functional test

### CODE REVIEW

**Comment by TimAbraldes** [comment]
!!! it passed

Removing the WIP tag

**Comment by TimAbraldes** [comment]
@darkwing would you mind taking a look at how I've set up Intern to work with Platatus? Let me know if anything looks out of place and if it seems like this is a robust way to test the project

**Comment by digitarald** [comment]
Can you r? @darkwing ?

**Comment by darkwing** [comment]
Getting test failure:  https://gist.github.com/darkwing/34ecb9695a2ff5c1f483

Likely due to pre-merge-conflict resolution  commits

**Comment by darkwing** [comment]
When I manually start a selenium JAR file I've downloaded in the past (`java -jar selenium-server-standalone-2.47.1.jar`), everything works.  When I don't manually start the selenium JAR, I receive a fatal error:

https://gist.github.com/darkwing/2372d53b25dbbca723a7

Please confirm that if a local selenium is found, it's up to the developer to manually start it.

Also, should we rebase and squash all these commits?

**Comment by digitarald** [comment]
Seems like it works in travis, is that enough confirmation @darkwing ?

**Comment by darkwing** [comment]
Yep, works for me @digitarald

**Comment by TimAbraldes** [comment]
It should work without any intervention on your part (like starting the JAR manually). What platform are you on? Could you check the tests/var/selenium.log file for anything descriptive?This group has had discussions about squashing commits in the past and has always decided against it. mozilla/platatus wrote:When I manually start a selenium JAR file I've downloaded in the past (java -jar selenium-server-standalone-2.47.1.jar), everything works.  When I don't manually start the selenium JAR, I receive a fatal error:

https://gist.github.com/darkwing/2372d53b25dbbca723a7

Please confirm that if a local selenium is found, it's up to the developer to manually start it.

Also, should we rebase and squash all these commits?

—Reply to this email directly or view it on GitHub.


  
  


Sent Using Firefox OS

**Pull request merged**
