### PR TITLE
Add anchor link to features

### LINKED ISSUE #196: Add anchor link to features
Link icon :link: similar to github markdown headers, reveal on hover.

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #196.

### CODE REVIEW

**Comment by digitarald** [comment]
@marco-c could you rebase please so reviewing on heroku works?

**Comment by marco-c** [comment]
I can't see the logs for the failing deployment (Heroku says I don't have access to the platatus-pr-195 app).

**Comment by digitarald** [comment]
Weirdly Heroku didn't show a problem, this is the build: https://platatus-pr-195.herokuapp.com/

**Comment by digitarald** [comment]
Could we add some opacity to the link to make it less center of attention and add some more space between the icon and the text?

Also, the icon seems to push out the while feature text: screenshot

**Comment by digitarald** [comment]
Regarding the 3rd feedback, see the space between margin and content

For comparison, current website:

-[org](https://cldup.com/i4MdBH3pwp-2000x2000.png)

**Comment by digitarald** [comment]
Did it build correctly? now

**Comment by marco-c** [comment]
> Did it build correctly?

Yes, I forgot to update the file... Should be fixed now.

**Comment by marco-c** [comment]
platatus

**Comment by marco-c** [comment]
^ this is what it looks like now.

**Pull request merged**
